### ISSUE TITLE
Suggestion: provide a flake

### ISSUE THREAD

**Issue by maralorn** [Mic92/nix-index-database#12]
I had the following idea:

This repo could provide a flake similar to this:

```
{
 inputs = {
  database = {
   type = "tarball";
   url = "https://github.com/Mic92/nix-index-database/releases/download/2022-05-22/index-x86_64-linux";   
   };
 }
 outputs = {database} : {
  inherit database;
 }
}
```

The github action could update the url and the lockfile.
This way flake users could include the database purely in their system and update it with `flake update`.

What do you think?

**Comment by lilyball** [comment]
This looks like a great solution to the problem I've been trying to figure out, which is how to integrate this into my setup. I don't really want to write a service that periodically tries to wget the latest release, and AFAIK Nix has no direct support for GitHub Releases. I've been considering scripting my `nix flake update` step to also resolve the latest release but that's annoying. Having some reference to the new release end up in `main` would be really helpful, and adding a `flake.nix` as you suggested seems like the best way to handle this.

**Comment by Mic92** [comment]
Sounds good. I am accepting PRs for this.

**Comment by Mic92** [comment]
It could be also just a normal package of an flake input with the same effect. Than one can use `nix-update` to track releases.

**Comment by lilyball** [comment]
Trying to replicate this locally, we can't actually use flake inputs for this. `type = "tarball"` requires it to actually be a tarball, which it isn't, and there's no other type that means "download this as just a file". This could perhaps skip the inputs and define the outputs using `builtins.fetchurl`.

One potential concern here is that without having the file hashes, that will end up refetching if it's been at least an hour (by default) since the last fetch. I don't know offhand if it's able to use ETag or Last-Modified-Since to avoid the redownload (I certainly hope so) but at a minimum it will do network access for this. If possible, it would be great if the CI action that updates the flake would calculate the hash and include that too.

**Comment by lilyball** [comment]
Oops, pure evaluation mode requires the hash for `fetchurl`. This makes it rather difficult to implement this locally in a pure manner without actually downloading the index while updating the URLs.

**Comment by maralorn** [comment]
@lilyball I think what we can do is run nix-prefetch-url and put the output output hash with the url into the flake. Then we don‘t manage the url as a flake input, but that’s no problem I think.
