### ISSUE TITLE
Also provide `comma` integration?

### ISSUE THREAD

**Issue by amesgen** [Mic92/nix-index-database#33]
Thanks for the new modules, they are very convenient! I am wondering whether they could also provide a [`comma`](https://github.com/nix-community/comma) which uses the pre-built database (without having to recompile `comma`).

My current solution for this is to set
```nix
home.file."${hm.config.xdg.cacheHome}/nix-index/files".source =
  inputs.nix-index-database.legacyPackages.${pkgs.stdenv.system}.database;
```
which is then used by stock `comma`, but maybe there is a cleaner approach.

**Comment by R-VdP** [comment]
I looked at using our wrapped `nix-locate` with `comma`, but the issue is that they have hard-coded the database location in order to be able to detect its presence and warn if it's outdated. And I think it will be complicated to detect the difference between a `nix-locate` that comes with a database included (like the one from this repo), and one where the database is maintained manually.

So I think for now that what you are doing is the best solution.
It will not duplicate the database, as you're just symlinking to the same file in the nix store.

**Comment by amesgen** [comment]
Thanks for taking a look, opened #34 for the symlinking approach :+1:
